"""initial

Revision ID: 20987921f254
Revises: eef82fc10eff
Create Date: 2024-01-07 13:44:46.576005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20987921f254'
down_revision: Union[str, None] = 'eef82fc10eff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('limites_proposta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('id_proposta', sa.Integer(), nullable=True),
    sa.Column('id_contraparte', sa.Integer(), nullable=True),
    sa.Column('tipo_limite', sa.Integer(), nullable=True),
    sa.Column('rating', sa.String(), nullable=True),
    sa.Column('valor_limite', sa.DECIMAL(), nullable=True),
    sa.Column('valor_carteira', sa.DECIMAL(), nullable=True),
    sa.Column('carteira_mwm', sa.DECIMAL(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['id_contraparte'], ['propostas_contraparte.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_limites_proposta_id'), 'limites_proposta', ['id'], unique=False)
    op.drop_constraint('propostas_contraparte_id_contraparte_fkey', 'propostas_contraparte', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('propostas_contraparte_id_contraparte_fkey', 'propostas_contraparte', 'tipos_rating_cliente', ['id_contraparte'], ['id'])
    op.drop_index(op.f('ix_limites_proposta_id'), table_name='limites_proposta')
    op.drop_table('limites_proposta')
    # ### end Alembic commands ###
