"""initial

Revision ID: a321318d726c
Revises: d8e228d02763
Create Date: 2024-01-07 19:33:47.975590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a321318d726c'
down_revision: Union[str, None] = 'd8e228d02763'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observacoes_proposta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('id_proposta', sa.Integer(), nullable=True),
    sa.Column('id_contraparte', sa.Integer(), nullable=True),
    sa.Column('tipo_observacao', sa.Integer(), nullable=True),
    sa.Column('observacao_vigente', sa.String(), nullable=True),
    sa.Column('observacao_sugerido', sa.String(), nullable=True),
    sa.Column('observacao_aprovado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['id_contraparte'], ['propostas_contraparte.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observacoes_proposta_id'), 'observacoes_proposta', ['id'], unique=False)
    op.drop_index('ix_observacoes_roposta _id', table_name='observacoes_roposta ')
    op.drop_table('observacoes_roposta ')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observacoes_roposta ',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"observacoes_roposta _id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('id_cliente', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_proposta', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_contraparte', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo_observacao', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('observacao_vigente', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('observacao_sugerido', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('observacao_aprovado', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], name='observacoes_roposta _id_cliente_fkey'),
    sa.ForeignKeyConstraint(['id_contraparte'], ['propostas_contraparte.id'], name='observacoes_roposta _id_contraparte_fkey'),
    sa.PrimaryKeyConstraint('id', name='observacoes_roposta _pkey')
    )
    op.create_index('ix_observacoes_roposta _id', 'observacoes_roposta ', ['id'], unique=False)
    op.drop_index(op.f('ix_observacoes_proposta_id'), table_name='observacoes_proposta')
    op.drop_table('observacoes_proposta')
    # ### end Alembic commands ###
