"""initial

Revision ID: d8e228d02763
Revises: 20987921f254
Create Date: 2024-01-07 15:41:46.260419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8e228d02763'
down_revision: Union[str, None] = '20987921f254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observacoes_roposta ',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('id_proposta', sa.Integer(), nullable=True),
    sa.Column('id_contraparte', sa.Integer(), nullable=True),
    sa.Column('tipo_observacao', sa.Integer(), nullable=True),
    sa.Column('observacao_vigente', sa.String(), nullable=True),
    sa.Column('observacao_sugerido', sa.String(), nullable=True),
    sa.Column('observacao_aprovado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['id_contraparte'], ['propostas_contraparte.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observacoes_roposta _id'), 'observacoes_roposta ', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_observacoes_roposta _id'), table_name='observacoes_roposta ')
    op.drop_table('observacoes_roposta ')
    # ### end Alembic commands ###
